module.exports = {
	theme: {
		fontFamily: {
			"eina-bold": ["Eina\\ Bold"],
			inter: [
				"Inter",
				"-apple-system",
				"BlinkMacSystemFont",
				"Segoe UI",
				"Roboto",
				"Oxygen",
				"Ubuntu",
				"Cantarell",
				"Helvetica Neue",
				"sans-serif",
				"Arial",
			],
			"inter-light": [
				"Inter\\ Light",
				"-apple-system",
				"BlinkMacSystemFont",
				"Segoe UI",
				"Roboto",
				"Oxygen",
				"Ubuntu",
				"Cantarell",
				"Helvetica Neue",
				"sans-serif",
				"Arial",
			],
		},
		backgroundColor: (theme) => ({
			...theme("colors"),
			body: "#FCFCFC",
			"darkest-blue": "#091540",
			"grey-blue": "#3D518C",
			"flower-blue": "#7692FF",
			"rich-blue": "#1B2CC1",
		}),
		borderColor: (theme) => ({
			...theme("colors"),
			"darkest-blue": "#091540",
			"grey-blue": "#3D518C",
			"flower-blue": "#7692FF",
			"rich-blue": "#1B2CC1",
		}),
		textColor: (theme) => ({
			...theme("colors"),
			"darkest-blue": "#091540",
			"grey-blue": "#3D518C",
			"flower-blue": "#7692FF",
			"rich-blue": "#1B2CC1",
		}),
	},
	variants: {},
	plugins: [],
};
